# permissions for end users to edit mysqlbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysqlbackup
    app.kubernetes.io/managed-by: kustomize
  name: mysqlbackup-editor-role
rules:
- apiGroups:
  - webapp.xingzai.cn
  resources:
  - mysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.xingzai.cn
  resources:
  - mysqlbackups/status
  verbs:
  - get
