---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.xingzai.cn
  resources:
  - mysqlbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.xingzai.cn
  resources:
  - mysqlbackups/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.xingzai.cn
  resources:
  - mysqlbackups/status
  verbs:
  - get
  - patch
  - update
